name: crucible-ci

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/cdm-ci.yaml
    - 'docs/**'
  workflow_dispatch:

jobs:
  call-core-crucible-ci:
    uses: perftool-incubator/crucible-ci/.github/workflows/core-crucible-ci.yaml@main
    with:
      ci_target: "CommonDataModel"
      ci_target_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
    secrets:
      registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
